### PR TITLE
Add component setup and dimension hints

### PR DESCRIPTION
**Pull request by ndabAP**
Just some small additions which I missed at first.

### CODE REVIEW

**Comment by dattn** [comment]
I think you should specify that the actual pixel size depends on the grid size, as seen here
https://github.com/dattn/dnd-grid/blob/master/src/demo.vue#L81

**Comment by ndabAP** [comment]
So, 

```js
gridSize: {
  w: 101
}
```

and 

```js
position: {
  w: 2
}
```

results in 202 pixels?

**Comment by dattn** [comment]
Yes.

The `position` property, represents the position in the virtual grid.
And the size of one cell in this grid is defined with the `gridSize` property.

**Comment by ndabAP** [comment]
Please see my latest commit.

**Comment by dattn** [comment]
Looks good to me

**Comment by dattn** [comment]
Thank you for the pull request.
All Pull request should go to the develop branch, because my master branch represents the latest released version :)

**Pull request merged**
