### PR TITLE
Added drag events to container

### PR DESCRIPTION
**Pull request by stanogurnik**
Adding drag events to container:

Specially `drag:end` event is useful when saving state of layout to server

### CODE REVIEW

**Comment by stanogurnik** [comment]
@dattn can you please look at this ?

**Comment by stanogurnik** [comment]
Yes and no. Update layout is called every time some item is moved on grid, so simple drag of object generates x events (if item moves from x:1 -> x:5 it generates 5 events during this user action), but you want to save state when relevant - so when user stops dragging.

**Comment by stanogurnik** [comment]
@dattn can you please look at this ?

**Comment by dattn** [comment]
Sorry, i'm really busy at the moment.
But your pull request looks good, I will release a new version today.

**Pull request merged**
